extends:
  - '@commitlint/config-conventional'

plugins:
  - commitlint-plugin-jira-rules

rules:
  scope-empty:
    - 2
    - never
  subject-case:
    - 2
    - always
    - lower-case
  jira-task-id-max-length:
    - 1
    - always
    - 120
