/**
 * Legacy Tool → Pscode Migration
 *
 * Detects projects using the old "openspec" structure and migrates them
 * cleanly to Pscode: deletes old skills/commands generated by openspec
 * (opsx-* prefix), renames the .openspec/ folder to pscode/, and
 * migrates any stale config fields.
 *
 * Migration is triggered automatically during `pscode init` when an
 * .openspec/ directory is detected. The user is prompted to confirm before
 * any changes are made.
 */

import path from 'path';
import { promises as fs, type Dirent } from 'fs';
import chalk from 'chalk';
import { AI_TOOLS } from './config.js';
import { CommandAdapterRegistry } from './command-generation/index.js';
import { ALL_WORKFLOWS } from './profiles.js';
import { FileSystemUtils } from '../utils/file-system.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Candidate directory names used by the old openspec tool.
 * Check both "openspec" (without dot) and ".openspec" (with dot).
 */
const OPENSPEC_DIR_CANDIDATES = ['openspec', '.openspec'];

/** Old skill prefix used by openspec */
const OPENSPEC_SKILL_PREFIX = 'opsx-';

/** Old slash command prefix used by openspec */
const OPENSPEC_COMMAND_PREFIX = 'opsx-';

/** Old slash command namespaces (subdirectories inside commands/) to remove */
const OPENSPEC_COMMAND_DIRS = ['opsx', 'openspec'];

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface LegacyToolDetectionResult {
  /** Whether an openspec/ or .openspec/ directory was found */
  hasLegacyDir: boolean;
  /** Full path to the openspec/ (or .openspec/) directory that was found */
  legacyDirPath: string;
  /** Directory name as it appears on disk ("openspec" or ".openspec") */
  legacyDirName: string;
  /** Old opsx-* skill files found across all tool dirs */
  legacySkillFiles: string[];
  /** Old opsx-* / openspec command files found across all tool dirs */
  legacyCommandFiles: string[];
  /** Whether any legacy tool artifacts were found */
  hasLegacyArtifacts: boolean;
}

export interface LegacyToolMigrationResult {
  /** Whether openspec/ (or .openspec/) was renamed to pscode/ */
  renamedDir: boolean;
  /** Whether openspec/ (or .openspec/) content was merged into an existing pscode/ */
  mergedDir: boolean;
  /** The directory name that was migrated ("openspec" or ".openspec") */
  sourceDirName: string;
  /** Skill files deleted */
  deletedSkills: string[];
  /** Command files/dirs deleted */
  deletedCommands: string[];
  /** Files copied during merge (relative to project root) */
  mergedFiles: string[];
  /** Errors that occurred */
  errors: string[];
}

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

/**
 * Detects legacy tool artifacts in a project.
 * Checks for both "openspec/" and ".openspec/" directory names.
 */
export async function detectLegacyToolArtifacts(
  projectPath: string
): Promise<LegacyToolDetectionResult> {
  // Find whichever openspec directory exists (prefer "openspec" over ".openspec")
  let legacyDirName = OPENSPEC_DIR_CANDIDATES[0];
  let legacyDirPath = path.join(projectPath, legacyDirName);
  let hasLegacyDir = false;

  for (const candidate of OPENSPEC_DIR_CANDIDATES) {
    const candidatePath = path.join(projectPath, candidate);
    if (await FileSystemUtils.directoryExists(candidatePath)) {
      legacyDirName = candidate;
      legacyDirPath = candidatePath;
      hasLegacyDir = true;
      break;
    }
  }

  const legacySkillFiles: string[] = [];
  const legacyCommandFiles: string[] = [];

  // Scan all known tool skill directories for opsx-* skill dirs
  for (const tool of AI_TOOLS) {
    if (!tool.skillsDir) continue;

    const skillsDir = path.join(projectPath, tool.skillsDir, 'skills');
    if (await FileSystemUtils.directoryExists(skillsDir)) {
      try {
        const entries = await fs.readdir(skillsDir);
        for (const entry of entries) {
          // Match both opsx-* prefixed dirs and any dir containing "openspec"
          if (entry.startsWith(OPENSPEC_SKILL_PREFIX) || entry.includes('openspec')) {
            legacySkillFiles.push(path.join(tool.skillsDir, 'skills', entry));
          }
        }
      } catch {
        // ignore
      }
    }

    // Scan for old command files (opsx-*.md or openspec/ dir)
    const adapter = CommandAdapterRegistry.get(tool.value);
    if (!adapter) continue;

    // Check for old opsx-prefixed command files using the adapter's base dir
    for (const workflow of ALL_WORKFLOWS) {
      const cmdPath = adapter.getFilePath(workflow);
      const fullPath = path.isAbsolute(cmdPath) ? cmdPath : path.join(projectPath, cmdPath);
      const dir = path.dirname(fullPath);
      const basename = path.basename(fullPath);

      // Check for opsx-prefixed variant in the same directory
      const opsPrefixedName = basename.replace(/^pastel-/, OPENSPEC_COMMAND_PREFIX);
      if (opsPrefixedName !== basename) {
        const opsPrefixedPath = path.join(dir, opsPrefixedName);
        try {
          await fs.access(opsPrefixedPath);
          const rel = path.relative(projectPath, opsPrefixedPath).replace(/\\/g, '/');
          legacyCommandFiles.push(rel);
        } catch {
          // file doesn't exist
        }
      }
    }

    // Check for old opsx/ and openspec/ command directories (claude/gemini-style)
    const toolDir = path.join(projectPath, tool.skillsDir);
    for (const cmdDirName of OPENSPEC_COMMAND_DIRS) {
      const legacyCmdDir = path.join(toolDir, 'commands', cmdDirName);
      if (await FileSystemUtils.directoryExists(legacyCmdDir)) {
        const rel = path.relative(projectPath, legacyCmdDir).replace(/\\/g, '/');
        legacyCommandFiles.push(rel + '/');
      }
    }
  }

  const hasLegacyArtifacts =
    hasLegacyDir ||
    legacySkillFiles.length > 0 ||
    legacyCommandFiles.length > 0;

  return {
    hasLegacyDir,
    legacyDirPath,
    legacyDirName,
    legacySkillFiles,
    legacyCommandFiles,
    hasLegacyArtifacts,
  };
}

// ---------------------------------------------------------------------------
// Summary display
// ---------------------------------------------------------------------------

/**
 * Formats a human-readable summary of what was detected.
 * @param pscodeAlreadyExists - when true, shows merge instead of rename
 */
export function formatLegacyToolDetectionSummary(
  detection: LegacyToolDetectionResult,
  pscodeAlreadyExists = false
): string {
  const lines: string[] = [];

  lines.push(chalk.bold('This project uses the OpenSpec framework'));
  lines.push('');
  lines.push('OpenSpec and Pscode share the same workflow philosophy, but Pscode');
  lines.push('is the evolution of the framework — with better tooling, more AI integrations,');
  lines.push('and active development going forward.');
  lines.push('');
  lines.push('Migrating will:');
  lines.push('');

  if (detection.hasLegacyDir) {
    const dirName = detection.legacyDirName;
    if (pscodeAlreadyExists) {
      lines.push(
        `  • Merge ${chalk.cyan(dirName + '/changes')} and ${chalk.cyan(dirName + '/specs')} into ${chalk.cyan('pscode/')} — your work stays intact`
      );
      lines.push(`  • Remove ${chalk.cyan(dirName + '/')} after merge`);
    } else {
      lines.push(`  • Move ${chalk.cyan(dirName + '/')} → ${chalk.cyan('pscode/')} — all your changes and specs come along`);
    }
  }

  if (detection.legacySkillFiles.length > 0) {
    lines.push(
      `  • Remove ${detection.legacySkillFiles.length} old opsx-* / openspec-* skill director${detection.legacySkillFiles.length === 1 ? 'y' : 'ies'}`
    );
    for (const f of detection.legacySkillFiles) {
      lines.push(`      ${chalk.dim(f + '/')}`);
    }
  }

  if (detection.legacyCommandFiles.length > 0) {
    lines.push(
      `  • Remove ${detection.legacyCommandFiles.length} old opsx/ / openspec/ command folder${detection.legacyCommandFiles.length === 1 ? '' : 's'} and file${detection.legacyCommandFiles.length === 1 ? '' : 's'}`
    );
    for (const f of detection.legacyCommandFiles) {
      lines.push(`      ${chalk.dim(f)}`);
    }
  }

  lines.push('');
  lines.push(chalk.dim('Fresh Pscode skills and commands will be installed right after.'));

  return lines.join('\n');
}

/**
 * Formats a summary of what was done during migration.
 */
export function formatLegacyToolMigrationSummary(
  result: LegacyToolMigrationResult
): string {
  const lines: string[] = [];

  if (result.renamedDir) {
    lines.push(`  ✓ Renamed ${result.sourceDirName}/ → pscode/`);
  }

  if (result.mergedDir) {
    lines.push(`  ✓ Merged ${result.sourceDirName}/ content into pscode/`);
    for (const f of result.mergedFiles) {
      lines.push(`      ${chalk.dim(f)}`);
    }
  }

  for (const f of result.deletedSkills) {
    lines.push(`  ✓ Deleted skill: ${f}`);
  }

  for (const f of result.deletedCommands) {
    lines.push(`  ✓ Deleted command: ${f}`);
  }

  for (const e of result.errors) {
    lines.push(`  ⚠ ${e}`);
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Migration
// ---------------------------------------------------------------------------

/** Subdirectories inside .openspec/ that carry user data worth migrating. */
const OPENSPEC_DATA_DIRS = ['changes', 'specs'];

/**
 * Recursively copies files from `src` into `dst`.
 * Existing destination files are never overwritten (skip-if-exists strategy).
 * Returns the list of relative paths (relative to `src`) that were copied.
 */
async function mergeDirectoryInto(
  src: string,
  dst: string,
  baseRel = ''
): Promise<string[]> {
  const copied: string[] = [];

  let entries: Dirent[];
  try {
    entries = await fs.readdir(src, { withFileTypes: true });
  } catch {
    return copied; // src doesn't exist or can't be read
  }

  await fs.mkdir(dst, { recursive: true });

  for (const entry of entries) {
    const rel = baseRel ? `${baseRel}/${entry.name}` : entry.name;
    const srcPath = path.join(src, entry.name);
    const dstPath = path.join(dst, entry.name);

    if (entry.isDirectory()) {
      const sub = await mergeDirectoryInto(srcPath, dstPath, rel);
      copied.push(...sub);
    } else {
      // Skip if destination already exists
      const dstExists = await fs.stat(dstPath).then(() => true).catch(() => false);
      if (!dstExists) {
        try {
          await fs.copyFile(srcPath, dstPath);
          copied.push(rel);
        } catch {
          // best-effort
        }
      }
    }
  }

  return copied;
}

/**
 * Runs the legacy tool → pscode migration.
 * - Deletes old opsx-* skill directories
 * - Deletes old openspec command files/directories
 * - If pscode/ doesn't exist: renames .openspec/ → pscode/
 * - If pscode/ already exists: merges changes/ and specs/ from .openspec/
 *   into pscode/ (existing files are never overwritten), then removes .openspec/
 */
export async function runLegacyToolMigration(
  projectPath: string,
  detection: LegacyToolDetectionResult
): Promise<LegacyToolMigrationResult> {
  const result: LegacyToolMigrationResult = {
    renamedDir: false,
    mergedDir: false,
    sourceDirName: detection.legacyDirName,
    deletedSkills: [],
    deletedCommands: [],
    mergedFiles: [],
    errors: [],
  };

  // 1. Delete old opsx-* skill directories
  for (const relPath of detection.legacySkillFiles) {
    const fullPath = path.join(projectPath, relPath);
    try {
      await fs.rm(fullPath, { recursive: true, force: true });
      result.deletedSkills.push(relPath);
    } catch (err: any) {
      result.errors.push(`Could not delete skill ${relPath}: ${err.message}`);
    }
  }

  // 2. Delete old openspec command files / directories
  for (const relPath of detection.legacyCommandFiles) {
    const fullPath = path.join(projectPath, relPath.replace(/\/$/, ''));
    try {
      const stat = await fs.stat(fullPath).catch(() => null);
      if (stat?.isDirectory()) {
        await fs.rm(fullPath, { recursive: true, force: true });
      } else if (stat) {
        await fs.unlink(fullPath);
      }
      result.deletedCommands.push(relPath);
    } catch (err: any) {
      result.errors.push(`Could not delete command ${relPath}: ${err.message}`);
    }
  }

  // 3. Migrate .openspec/ directory
  if (detection.hasLegacyDir) {
    const pscodePath = path.join(projectPath, 'pscode');
    const pscodeExists = await FileSystemUtils.directoryExists(pscodePath);

    if (pscodeExists) {
      // pscode/ already exists — merge user data subdirectories, then remove .openspec/
      for (const subDir of OPENSPEC_DATA_DIRS) {
        const srcSub = path.join(detection.legacyDirPath, subDir);
        const dstSub = path.join(pscodePath, subDir);
        const copied = await mergeDirectoryInto(srcSub, dstSub, subDir);
        result.mergedFiles.push(...copied);
      }

      try {
        await fs.rm(detection.legacyDirPath, { recursive: true, force: true });
        result.mergedDir = true;
      } catch (err: any) {
        result.errors.push(`Could not remove ${detection.legacyDirName}/ after merge: ${err.message}`);
      }
    } else {
      // pscode/ doesn't exist yet — simple rename
      try {
        await fs.rename(detection.legacyDirPath, pscodePath);
        result.renamedDir = true;
      } catch (err: any) {
        result.errors.push(`Could not rename ${detection.legacyDirName}/ → pscode/: ${err.message}`);
      }
    }
  }

  return result;
}

/**
 * Returns true when a `pscode/` directory already exists at the given project path.
 * Used by the init command to pass the correct context to formatLegacyToolDetectionSummary.
 */
export async function pscodeDirExists(projectPath: string): Promise<boolean> {
  return FileSystemUtils.directoryExists(path.join(projectPath, 'pscode'));
}
